### ISSUE TITLE
Pretrained models giving Out of memory error.

### ISSUE THREAD

**Issue by LloydDuhon** [FilipAndersson245/cartoon-gan#9]
Is there a way to reduce the memory requirements to that of a 4 GB card?

RuntimeError: CUDA out of memory. Tried to allocate 5.72 GiB

**Comment by FilipAndersson245** [comment]
best way to allow training on low VRAM cards is to lower the batch_size of each iteration. This may affect the quality of the generated samples. otherwise if that's not enough, try lower the image resolution, currently its set to 256x256 for the training, but it should not severely lower the result if you lower it to 224.
